return {
  'mistweaverco/kulala.nvim',
  opts = {},
  config = function()
    local kulala = require 'kulala'

    vim.keymap.set('n', '<leader>ke', function()
      kulala.run()
    end, { desc = '[K]ulala [R]un' })
    vim.keymap.set('n', '<leader>ka', function()
      kulala.run_all()
    end, { desc = '[K]ulala [R]un all' })
    vim.keymap.set('n', '<leader>kr', function()
      kulala.replay()
    end, { desc = '[K]ulala [R]eplay' })
    vim.keymap.set('n', '<leader>ki', function()
      kulala.inspect()
    end, { desc = '[K]ulala [I]nspect' })
    vim.keymap.set('n', '<leader>ks', function()
      kulala.show_stats()
    end, { desc = '[K]ulala [S]how stats' })
    vim.keymap.set('n', '<leader>kp', function()
      kulala.scratchpad()
    end, { desc = '[K]ulala [S]cratch pad' })
    vim.keymap.set('n', '<leader>kc', function()
      kulala.copy()
    end, { desc = '[K]ulala [C]opy' })
    vim.keymap.set('n', '<leader>kf', function()
      kulala.from_curl()
    end, { desc = '[K]ulala [F]rom cURL' })
    vim.keymap.set('n', '<leader>kx', function()
      kulala.close()
    end, { desc = '[K]ulala [C]lose' })
    vim.keymap.set('n', '<leader>kt', function()
      kulala.toggle_view()
    end, { desc = '[K]ulala [T]oggle view' })
    vim.keymap.set('n', '<leader>km', function()
      kulala.search()
    end, { desc = '[K]ulala [S]earch' })
    vim.keymap.set('n', '<leader>kb', function()
      kulala.jump_prev()
    end, { desc = '[K]ulala [P]revious' })
    vim.keymap.set('n', '<leader>kn', function()
      kulala.jump_next()
    end, { desc = '[K]ulala [N]ext' })
    vim.keymap.set('n', '<leader>kj', '<cmd>%!jq<cr>', { desc = '[K]ulala [F]ormat with jq' })
  end,
}
